"""add_knowledge_core_and_health_check

Revision ID: 214dbe10b9e5
Revises: 390eab233bf5
Create Date: 2026-09-23 12:08:44.061906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '214dbe10b9e5'
down_revision: Union[str, Sequence[str], None] = '390eab233bf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_sources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_code', sa.String(length=50), nullable=False),
    sa.Column('authority_name', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('reference_url', sa.String(length=500), nullable=True),
    sa.Column('citation', sa.Text(), nullable=True),
    sa.Column('jurisdiction', sa.String(length=10), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('reviewed_by', sa.String(length=100), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_sources_source_code'), 'knowledge_sources', ['source_code'], unique=True)
    op.create_index(op.f('ix_knowledge_sources_source_type'), 'knowledge_sources', ['source_type'], unique=False)
    op.create_table('knowledge_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('knowledge_code', sa.String(length=50), nullable=False),
    sa.Column('domain', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('jurisdiction', sa.String(length=10), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_until', sa.Date(), nullable=True),
    sa.Column('rule_version', sa.Integer(), nullable=False),
    sa.Column('tally_version_pattern', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['knowledge_sources.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_items_domain'), 'knowledge_items', ['domain'], unique=False)
    op.create_index(op.f('ix_knowledge_items_knowledge_code'), 'knowledge_items', ['knowledge_code'], unique=True)
    op.create_index(op.f('ix_knowledge_items_source_id'), 'knowledge_items', ['source_id'], unique=False)
    op.create_index(op.f('ix_knowledge_items_status'), 'knowledge_items', ['status'], unique=False)
    op.create_table('company_knowledge_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('accounting_policy_references', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('gst_jurisdiction_state', sa.String(length=50), nullable=True),
    sa.Column('industry_sector', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_knowledge_profiles_company_id'), 'company_knowledge_profiles', ['company_id'], unique=True)
    op.create_table('decision_memories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('finding_code', sa.String(length=50), nullable=False),
    sa.Column('rule_code', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_name', sa.String(length=255), nullable=False),
    sa.Column('current_state', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('recommended_state', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('human_decision', sa.String(length=50), nullable=False),
    sa.Column('decision_reason', sa.Text(), nullable=False),
    sa.Column('actor_id', sa.String(length=100), nullable=False),
    sa.Column('actor_role', sa.String(length=50), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_memories_company_id'), 'decision_memories', ['company_id'], unique=False)
    op.create_index(op.f('ix_decision_memories_entity_name'), 'decision_memories', ['entity_name'], unique=False)
    op.create_index(op.f('ix_decision_memories_finding_code'), 'decision_memories', ['finding_code'], unique=False)
    op.create_index(op.f('ix_decision_memories_rule_code'), 'decision_memories', ['rule_code'], unique=False)
    op.create_table('forensic_scans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('tally_company_id', sa.Uuid(), nullable=True),
    sa.Column('scan_code', sa.String(length=50), nullable=False),
    sa.Column('scan_status', sa.String(length=30), nullable=False),
    sa.Column('ledgers_reviewed', sa.Integer(), nullable=False),
    sa.Column('findings_count', sa.Integer(), nullable=False),
    sa.Column('critical_count', sa.Integer(), nullable=False),
    sa.Column('review_recommended_count', sa.Integer(), nullable=False),
    sa.Column('healthy_count', sa.Integer(), nullable=False),
    sa.Column('gst_findings_count', sa.Integer(), nullable=False),
    sa.Column('duplicate_clusters_count', sa.Integer(), nullable=False),
    sa.Column('known_exceptions_count', sa.Integer(), nullable=False),
    sa.Column('overall_health', sa.String(length=30), nullable=False),
    sa.Column('scanned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tally_company_id'], ['tally_companies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forensic_scans_company_id'), 'forensic_scans', ['company_id'], unique=False)
    op.create_index(op.f('ix_forensic_scans_overall_health'), 'forensic_scans', ['overall_health'], unique=False)
    op.create_index(op.f('ix_forensic_scans_scan_code'), 'forensic_scans', ['scan_code'], unique=True)
    op.create_index(op.f('ix_forensic_scans_scan_status'), 'forensic_scans', ['scan_status'], unique=False)
    op.create_index(op.f('ix_forensic_scans_tally_company_id'), 'forensic_scans', ['tally_company_id'], unique=False)
    op.create_table('forensic_findings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scan_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('finding_code', sa.String(length=50), nullable=False),
    sa.Column('rule_code', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('entity_name', sa.String(length=255), nullable=False),
    sa.Column('severity', sa.String(length=30), nullable=False),
    sa.Column('fact_observed', sa.Text(), nullable=False),
    sa.Column('fact_details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('rule_triggered', sa.Text(), nullable=False),
    sa.Column('knowledge_code', sa.String(length=50), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('decision_status', sa.String(length=30), nullable=False),
    sa.Column('known_exception_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['known_exception_id'], ['decision_memories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scan_id'], ['forensic_scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forensic_findings_company_id'), 'forensic_findings', ['company_id'], unique=False)
    op.create_index(op.f('ix_forensic_findings_decision_status'), 'forensic_findings', ['decision_status'], unique=False)
    op.create_index(op.f('ix_forensic_findings_finding_code'), 'forensic_findings', ['finding_code'], unique=False)
    op.create_index(op.f('ix_forensic_findings_known_exception_id'), 'forensic_findings', ['known_exception_id'], unique=False)
    op.create_index(op.f('ix_forensic_findings_rule_code'), 'forensic_findings', ['rule_code'], unique=False)
    op.create_index(op.f('ix_forensic_findings_scan_id'), 'forensic_findings', ['scan_id'], unique=False)
    op.create_index(op.f('ix_forensic_findings_severity'), 'forensic_findings', ['severity'], unique=False)
    op.create_table('correction_proposals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('finding_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('target_entity_type', sa.String(length=50), nullable=False),
    sa.Column('target_entity_name', sa.String(length=255), nullable=False),
    sa.Column('target_tally_guid', sa.String(length=100), nullable=True),
    sa.Column('before_state', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('proposed_state', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('approval_id', sa.Uuid(), nullable=True),
    sa.Column('stale_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approval_id'], ['approvals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['finding_id'], ['forensic_findings.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_correction_proposals_approval_id'), 'correction_proposals', ['approval_id'], unique=False)
    op.create_index(op.f('ix_correction_proposals_company_id'), 'correction_proposals', ['company_id'], unique=False)
    op.create_index(op.f('ix_correction_proposals_finding_id'), 'correction_proposals', ['finding_id'], unique=False)
    op.create_index(op.f('ix_correction_proposals_status'), 'correction_proposals', ['status'], unique=False)
    op.create_table('correction_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('proposal_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('job_status', sa.String(length=30), nullable=False),
    sa.Column('execution_actor_id', sa.String(length=100), nullable=False),
    sa.Column('target_state_verified', sa.Boolean(), nullable=False),
    sa.Column('before_state_captured', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('after_state_captured', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('read_back_evidence', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['proposal_id'], ['correction_proposals.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_correction_jobs_company_id'), 'correction_jobs', ['company_id'], unique=False)
    op.create_index(op.f('ix_correction_jobs_job_status'), 'correction_jobs', ['job_status'], unique=False)
    op.create_index(op.f('ix_correction_jobs_proposal_id'), 'correction_jobs', ['proposal_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_correction_jobs_proposal_id'), table_name='correction_jobs')
    op.drop_index(op.f('ix_correction_jobs_job_status'), table_name='correction_jobs')
    op.drop_index(op.f('ix_correction_jobs_company_id'), table_name='correction_jobs')
    op.drop_table('correction_jobs')
    op.drop_index(op.f('ix_correction_proposals_status'), table_name='correction_proposals')
    op.drop_index(op.f('ix_correction_proposals_finding_id'), table_name='correction_proposals')
    op.drop_index(op.f('ix_correction_proposals_company_id'), table_name='correction_proposals')
    op.drop_index(op.f('ix_correction_proposals_approval_id'), table_name='correction_proposals')
    op.drop_table('correction_proposals')
    op.drop_index(op.f('ix_forensic_findings_severity'), table_name='forensic_findings')
    op.drop_index(op.f('ix_forensic_findings_scan_id'), table_name='forensic_findings')
    op.drop_index(op.f('ix_forensic_findings_rule_code'), table_name='forensic_findings')
    op.drop_index(op.f('ix_forensic_findings_known_exception_id'), table_name='forensic_findings')
    op.drop_index(op.f('ix_forensic_findings_finding_code'), table_name='forensic_findings')
    op.drop_index(op.f('ix_forensic_findings_decision_status'), table_name='forensic_findings')
    op.drop_index(op.f('ix_forensic_findings_company_id'), table_name='forensic_findings')
    op.drop_table('forensic_findings')
    op.drop_index(op.f('ix_forensic_scans_tally_company_id'), table_name='forensic_scans')
    op.drop_index(op.f('ix_forensic_scans_scan_status'), table_name='forensic_scans')
    op.drop_index(op.f('ix_forensic_scans_scan_code'), table_name='forensic_scans')
    op.drop_index(op.f('ix_forensic_scans_overall_health'), table_name='forensic_scans')
    op.drop_index(op.f('ix_forensic_scans_company_id'), table_name='forensic_scans')
    op.drop_table('forensic_scans')
    op.drop_index(op.f('ix_decision_memories_rule_code'), table_name='decision_memories')
    op.drop_index(op.f('ix_decision_memories_finding_code'), table_name='decision_memories')
    op.drop_index(op.f('ix_decision_memories_entity_name'), table_name='decision_memories')
    op.drop_index(op.f('ix_decision_memories_company_id'), table_name='decision_memories')
    op.drop_table('decision_memories')
    op.drop_index(op.f('ix_company_knowledge_profiles_company_id'), table_name='company_knowledge_profiles')
    op.drop_table('company_knowledge_profiles')
    op.drop_index(op.f('ix_knowledge_items_status'), table_name='knowledge_items')
    op.drop_index(op.f('ix_knowledge_items_source_id'), table_name='knowledge_items')
    op.drop_index(op.f('ix_knowledge_items_knowledge_code'), table_name='knowledge_items')
    op.drop_index(op.f('ix_knowledge_items_domain'), table_name='knowledge_items')
    op.drop_table('knowledge_items')
    op.drop_index(op.f('ix_knowledge_sources_source_type'), table_name='knowledge_sources')
    op.drop_index(op.f('ix_knowledge_sources_source_code'), table_name='knowledge_sources')
    op.drop_table('knowledge_sources')
    # ### end Alembic commands ###
