"""initial_schema

Revision ID: 390eab233bf5
Revises: 
Create Date: 2026-09-22 21:00:44.961933

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '390eab233bf5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
        op.create_table('organizations',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('legal_name', sa.String(length=255), nullable=False),
        sa.Column('slug', sa.String(length=100), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
        op.create_table('permissions',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('code', sa.String(length=100), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_permissions_code'), 'permissions', ['code'], unique=True)
        op.create_table('roles',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('organization_id', sa.Uuid(), nullable=True),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_roles_organization_id'), 'roles', ['organization_id'], unique=False)
        op.create_table('tally_instances',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('organization_id', sa.Uuid(), nullable=False),
        sa.Column('instance_name', sa.String(length=100), nullable=False),
        sa.Column('host', sa.String(length=255), nullable=False),
        sa.Column('port', sa.Integer(), nullable=False),
        sa.Column('tally_version', sa.String(length=100), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_tally_instances_organization_id'), 'tally_instances', ['organization_id'], unique=False)
        op.create_table('users',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('organization_id', sa.Uuid(), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('full_name', sa.String(length=255), nullable=False),
        sa.Column('hashed_password', sa.String(length=255), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
        op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
        op.create_table('bridges',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('organization_id', sa.Uuid(), nullable=False),
        sa.Column('tally_instance_id', sa.Uuid(), nullable=True),
        sa.Column('bridge_client_id', sa.String(length=100), nullable=False),
        sa.Column('api_key_hash', sa.String(length=255), nullable=False),
        sa.Column('os_platform', sa.String(length=100), nullable=True),
        sa.Column('status', sa.String(length=50), nullable=False),
        sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['tally_instance_id'], ['tally_instances.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_bridges_bridge_client_id'), 'bridges', ['bridge_client_id'], unique=True)
        op.create_index(op.f('ix_bridges_organization_id'), 'bridges', ['organization_id'], unique=False)
        op.create_index(op.f('ix_bridges_tally_instance_id'), 'bridges', ['tally_instance_id'], unique=False)
        op.create_table('companies',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('organization_id', sa.Uuid(), nullable=False),
        sa.Column('legal_name', sa.String(length=255), nullable=False),
        sa.Column('trade_name', sa.String(length=255), nullable=True),
        sa.Column('pan', sa.String(length=20), nullable=True),
        sa.Column('gstin', sa.String(length=20), nullable=True),
        sa.Column('currency', sa.String(length=10), nullable=False),
        sa.Column('financial_year_start', sa.Date(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('is_deleted', sa.Boolean(), nullable=False),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('deleted_by', sa.Uuid(), nullable=True),
        sa.Column('deletion_reason', sa.String(length=500), nullable=True),
        sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_companies_gstin'), 'companies', ['gstin'], unique=False)
        op.create_index(op.f('ix_companies_is_deleted'), 'companies', ['is_deleted'], unique=False)
        op.create_index('ix_companies_org_active', 'companies', ['organization_id', 'is_deleted'], unique=False)
        op.create_index(op.f('ix_companies_organization_id'), 'companies', ['organization_id'], unique=False)
        op.create_index(op.f('ix_companies_pan'), 'companies', ['pan'], unique=False)
        op.create_table('role_permissions',
        sa.Column('role_id', sa.Uuid(), nullable=False),
        sa.Column('permission_id', sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('role_id', 'permission_id')
        )
        op.create_table('user_roles',
        sa.Column('user_id', sa.Uuid(), nullable=False),
        sa.Column('role_id', sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('user_id', 'role_id')
        )
        op.create_table('audit_events',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('organization_id', sa.Uuid(), nullable=False),
        sa.Column('company_id', sa.Uuid(), nullable=True),
        sa.Column('actor_type', sa.String(length=50), nullable=False),
        sa.Column('actor_id', sa.String(length=255), nullable=False),
        sa.Column('action', sa.String(length=100), nullable=False),
        sa.Column('entity_type', sa.String(length=100), nullable=False),
        sa.Column('entity_id', sa.Uuid(), nullable=False),
        sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('event_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('ip_address', sa.String(length=50), nullable=True),
        sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
        op.create_index(op.f('ix_audit_events_company_id'), 'audit_events', ['company_id'], unique=False)
        op.create_index(op.f('ix_audit_events_entity_id'), 'audit_events', ['entity_id'], unique=False)
        op.create_index(op.f('ix_audit_events_entity_type'), 'audit_events', ['entity_type'], unique=False)
        op.create_index(op.f('ix_audit_events_organization_id'), 'audit_events', ['organization_id'], unique=False)
        op.create_index(op.f('ix_audit_events_recorded_at'), 'audit_events', ['recorded_at'], unique=False)
        op.create_index('ix_audit_org_action', 'audit_events', ['organization_id', 'action', 'recorded_at'], unique=False)
        op.create_table('branches',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('organization_id', sa.Uuid(), nullable=False),
        sa.Column('company_id', sa.Uuid(), nullable=False),
        sa.Column('branch_code', sa.String(length=50), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('state_code', sa.String(length=10), nullable=True),
        sa.Column('gstin', sa.String(length=20), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('is_deleted', sa.Boolean(), nullable=False),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('deleted_by', sa.Uuid(), nullable=True),
        sa.Column('deletion_reason', sa.String(length=500), nullable=True),
        sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('company_id', 'branch_code', name='uq_company_branch_code')
        )
        op.create_index(op.f('ix_branches_company_id'), 'branches', ['company_id'], unique=False)
        op.create_index(op.f('ix_branches_is_deleted'), 'branches', ['is_deleted'], unique=False)
        op.create_index('ix_branches_org_company', 'branches', ['organization_id', 'company_id'], unique=False)
        op.create_index(op.f('ix_branches_organization_id'), 'branches', ['organization_id'], unique=False)
        op.create_table('connections',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('bridge_id', sa.Uuid(), nullable=False),
        sa.Column('session_id', sa.String(length=100), nullable=False),
        sa.Column('ip_address', sa.String(length=50), nullable=True),
        sa.Column('connected_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('disconnected_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('disconnect_reason', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['bridge_id'], ['bridges.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_connections_bridge_id'), 'connections', ['bridge_id'], unique=False)
        op.create_index(op.f('ix_connections_session_id'), 'connections', ['session_id'], unique=False)
        op.create_table('documents',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('organization_id', sa.Uuid(), nullable=False),
        sa.Column('company_id', sa.Uuid(), nullable=False),
        sa.Column('document_number', sa.String(length=100), nullable=True),
        sa.Column('file_name', sa.String(length=255), nullable=False),
        sa.Column('file_type', sa.String(length=50), nullable=False),
        sa.Column('file_size_bytes', sa.Integer(), nullable=False),
        sa.Column('storage_path', sa.Text(), nullable=False),
        sa.Column('sha256_checksum', sa.String(length=64), nullable=False),
        sa.Column('status', sa.String(length=50), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('is_deleted', sa.Boolean(), nullable=False),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('deleted_by', sa.Uuid(), nullable=True),
        sa.Column('deletion_reason', sa.String(length=500), nullable=True),
        sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_documents_company_id'), 'documents', ['company_id'], unique=False)
        op.create_index(op.f('ix_documents_document_number'), 'documents', ['document_number'], unique=False)
        op.create_index(op.f('ix_documents_is_deleted'), 'documents', ['is_deleted'], unique=False)
        op.create_index(op.f('ix_documents_organization_id'), 'documents', ['organization_id'], unique=False)
        op.create_index(op.f('ix_documents_sha256_checksum'), 'documents', ['sha256_checksum'], unique=False)
        op.create_index('ix_documents_tenant_status', 'documents', ['organization_id', 'company_id', 'status'], unique=False)
        op.create_table('domain_exceptions',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('organization_id', sa.Uuid(), nullable=False),
        sa.Column('company_id', sa.Uuid(), nullable=True),
        sa.Column('entity_type', sa.String(length=100), nullable=False),
        sa.Column('entity_id', sa.Uuid(), nullable=True),
        sa.Column('exception_category', sa.String(length=50), nullable=False),
        sa.Column('severity', sa.String(length=20), nullable=False),
        sa.Column('error_message', sa.Text(), nullable=False),
        sa.Column('stack_trace', sa.Text(), nullable=True),
        sa.Column('is_resolved', sa.Boolean(), nullable=False),
        sa.Column('resolved_by_user_id', sa.Uuid(), nullable=True),
        sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['resolved_by_user_id'], ['users.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_domain_exceptions_company_id'), 'domain_exceptions', ['company_id'], unique=False)
        op.create_index(op.f('ix_domain_exceptions_organization_id'), 'domain_exceptions', ['organization_id'], unique=False)
        op.create_table('tally_companies',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('tally_instance_id', sa.Uuid(), nullable=False),
        sa.Column('company_id', sa.Uuid(), nullable=True),
        sa.Column('tally_guid', sa.String(length=255), nullable=False),
        sa.Column('company_name', sa.String(length=255), nullable=False),
        sa.Column('financial_year', sa.String(length=50), nullable=True),
        sa.Column('books_from', sa.Date(), nullable=True),
        sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('status', sa.String(length=50), nullable=False),
        sa.Column('company_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['tally_instance_id'], ['tally_instances.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('tally_instance_id', 'tally_guid', name='uq_tally_instance_guid')
        )
        op.create_index(op.f('ix_tally_companies_company_id'), 'tally_companies', ['company_id'], unique=False)
        op.create_index(op.f('ix_tally_companies_tally_guid'), 'tally_companies', ['tally_guid'], unique=False)
        op.create_index(op.f('ix_tally_companies_tally_instance_id'), 'tally_companies', ['tally_instance_id'], unique=False)
        op.create_table('document_versions',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('document_id', sa.Uuid(), nullable=False),
        sa.Column('version_number', sa.Integer(), nullable=False),
        sa.Column('storage_path', sa.Text(), nullable=False),
        sa.Column('sha256_checksum', sa.String(length=64), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_document_versions_document_id'), 'document_versions', ['document_id'], unique=False)
        op.create_table('items',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('organization_id', sa.Uuid(), nullable=False),
        sa.Column('company_id', sa.Uuid(), nullable=False),
        sa.Column('tally_company_id', sa.Uuid(), nullable=True),
        sa.Column('tally_guid', sa.String(length=255), nullable=True),
        sa.Column('tally_master_id', sa.Integer(), nullable=True),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('hsn_sac_code', sa.String(length=50), nullable=True),
        sa.Column('uom', sa.String(length=50), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('is_deleted', sa.Boolean(), nullable=False),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('deleted_by', sa.Uuid(), nullable=True),
        sa.Column('deletion_reason', sa.String(length=500), nullable=True),
        sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['tally_company_id'], ['tally_companies.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_items_company_id'), 'items', ['company_id'], unique=False)
        op.create_index(op.f('ix_items_is_deleted'), 'items', ['is_deleted'], unique=False)
        op.create_index(op.f('ix_items_organization_id'), 'items', ['organization_id'], unique=False)
        op.create_index(op.f('ix_items_tally_guid'), 'items', ['tally_guid'], unique=False)
        op.create_index('ix_items_tenant', 'items', ['organization_id', 'company_id', 'name'], unique=False)
        op.create_table('ledgers',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('organization_id', sa.Uuid(), nullable=False),
        sa.Column('company_id', sa.Uuid(), nullable=False),
        sa.Column('tally_company_id', sa.Uuid(), nullable=True),
        sa.Column('tally_guid', sa.String(length=255), nullable=True),
        sa.Column('tally_master_id', sa.Integer(), nullable=True),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('parent_group', sa.String(length=255), nullable=True),
        sa.Column('opening_balance', sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('is_deleted', sa.Boolean(), nullable=False),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('deleted_by', sa.Uuid(), nullable=True),
        sa.Column('deletion_reason', sa.String(length=500), nullable=True),
        sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['tally_company_id'], ['tally_companies.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_ledgers_company_id'), 'ledgers', ['company_id'], unique=False)
        op.create_index(op.f('ix_ledgers_is_deleted'), 'ledgers', ['is_deleted'], unique=False)
        op.create_index(op.f('ix_ledgers_organization_id'), 'ledgers', ['organization_id'], unique=False)
        op.create_index(op.f('ix_ledgers_tally_guid'), 'ledgers', ['tally_guid'], unique=False)
        op.create_index('ix_ledgers_tenant', 'ledgers', ['organization_id', 'company_id', 'name'], unique=False)
        op.create_table('parties',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('organization_id', sa.Uuid(), nullable=False),
        sa.Column('company_id', sa.Uuid(), nullable=False),
        sa.Column('tally_company_id', sa.Uuid(), nullable=True),
        sa.Column('tally_guid', sa.String(length=255), nullable=True),
        sa.Column('tally_master_id', sa.Integer(), nullable=True),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('party_type', sa.String(length=50), nullable=False),
        sa.Column('parent_group', sa.String(length=255), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('is_deleted', sa.Boolean(), nullable=False),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('deleted_by', sa.Uuid(), nullable=True),
        sa.Column('deletion_reason', sa.String(length=500), nullable=True),
        sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['tally_company_id'], ['tally_companies.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_parties_company_id'), 'parties', ['company_id'], unique=False)
        op.create_index(op.f('ix_parties_is_deleted'), 'parties', ['is_deleted'], unique=False)
        op.create_index(op.f('ix_parties_organization_id'), 'parties', ['organization_id'], unique=False)
        op.create_index(op.f('ix_parties_tally_guid'), 'parties', ['tally_guid'], unique=False)
        op.create_index('ix_parties_tenant', 'parties', ['organization_id', 'company_id', 'name'], unique=False)
        op.create_table('sync_jobs',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('organization_id', sa.Uuid(), nullable=False),
        sa.Column('company_id', sa.Uuid(), nullable=False),
        sa.Column('tally_company_id', sa.Uuid(), nullable=True),
        sa.Column('sync_type', sa.String(length=50), nullable=False),
        sa.Column('status', sa.String(length=50), nullable=False),
        sa.Column('cron_expression', sa.String(length=50), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['tally_company_id'], ['tally_companies.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_sync_jobs_company_id'), 'sync_jobs', ['company_id'], unique=False)
        op.create_index(op.f('ix_sync_jobs_organization_id'), 'sync_jobs', ['organization_id'], unique=False)
        op.create_table('document_extractions',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('document_version_id', sa.Uuid(), nullable=False),
        sa.Column('ai_provider', sa.String(length=50), nullable=False),
        sa.Column('model_name', sa.String(length=100), nullable=False),
        sa.Column('raw_response_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column('processing_time_ms', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_document_extractions_document_version_id'), 'document_extractions', ['document_version_id'], unique=False)
        op.create_table('party_identities',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('party_id', sa.Uuid(), nullable=False),
        sa.Column('gstin', sa.String(length=20), nullable=True),
        sa.Column('pan', sa.String(length=20), nullable=True),
        sa.Column('state_name', sa.String(length=100), nullable=True),
        sa.Column('registration_type', sa.String(length=50), nullable=True),
        sa.Column('address_line1', sa.Text(), nullable=True),
        sa.Column('pincode', sa.String(length=20), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['party_id'], ['parties.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_party_identities_gstin'), 'party_identities', ['gstin'], unique=False)
        op.create_index(op.f('ix_party_identities_pan'), 'party_identities', ['pan'], unique=False)
        op.create_index(op.f('ix_party_identities_party_id'), 'party_identities', ['party_id'], unique=False)
        op.create_table('sync_runs',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('sync_job_id', sa.Uuid(), nullable=False),
        sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('records_pulled', sa.Integer(), nullable=False),
        sa.Column('records_updated', sa.Integer(), nullable=False),
        sa.Column('status', sa.String(length=50), nullable=False),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['sync_job_id'], ['sync_jobs.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_sync_runs_sync_job_id'), 'sync_runs', ['sync_job_id'], unique=False)
        op.create_table('taxes',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('organization_id', sa.Uuid(), nullable=False),
        sa.Column('company_id', sa.Uuid(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('tax_type', sa.String(length=50), nullable=False),
        sa.Column('rate_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column('ledger_id', sa.Uuid(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['ledger_id'], ['ledgers.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_taxes_company_id'), 'taxes', ['company_id'], unique=False)
        op.create_index(op.f('ix_taxes_organization_id'), 'taxes', ['organization_id'], unique=False)
        op.create_table('accounting_proposals',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('organization_id', sa.Uuid(), nullable=False),
        sa.Column('company_id', sa.Uuid(), nullable=False),
        sa.Column('document_id', sa.Uuid(), nullable=False),
        sa.Column('document_extraction_id', sa.Uuid(), nullable=True),
        sa.Column('voucher_type', sa.String(length=50), nullable=False),
        sa.Column('proposed_date', sa.Date(), nullable=False),
        sa.Column('party_ledger_id', sa.Uuid(), nullable=True),
        sa.Column('total_amount', sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column('tax_amount', sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column('narration', sa.Text(), nullable=True),
        sa.Column('status', sa.String(length=50), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('is_deleted', sa.Boolean(), nullable=False),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('deleted_by', sa.Uuid(), nullable=True),
        sa.Column('deletion_reason', sa.String(length=500), nullable=True),
        sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['document_extraction_id'], ['document_extractions.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['party_ledger_id'], ['ledgers.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_accounting_proposals_company_id'), 'accounting_proposals', ['company_id'], unique=False)
        op.create_index(op.f('ix_accounting_proposals_document_id'), 'accounting_proposals', ['document_id'], unique=False)
        op.create_index(op.f('ix_accounting_proposals_is_deleted'), 'accounting_proposals', ['is_deleted'], unique=False)
        op.create_index(op.f('ix_accounting_proposals_organization_id'), 'accounting_proposals', ['organization_id'], unique=False)
        op.create_index('ix_proposals_tenant_status', 'accounting_proposals', ['organization_id', 'company_id', 'status'], unique=False)
        op.create_table('extraction_fields',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('document_extraction_id', sa.Uuid(), nullable=False),
        sa.Column('field_name', sa.String(length=100), nullable=False),
        sa.Column('field_value_text', sa.Text(), nullable=True),
        sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column('bounding_box', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['document_extraction_id'], ['document_extractions.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_extraction_fields_document_extraction_id'), 'extraction_fields', ['document_extraction_id'], unique=False)
        op.create_table('approvals',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('accounting_proposal_id', sa.Uuid(), nullable=False),
        sa.Column('user_id', sa.Uuid(), nullable=False),
        sa.Column('decision', sa.String(length=50), nullable=False),
        sa.Column('decision_timestamp', sa.DateTime(timezone=True), nullable=False),
        sa.Column('comments', sa.Text(), nullable=True),
        sa.Column('approval_step', sa.Integer(), nullable=False),
        sa.Column('authority_context', sa.String(length=100), nullable=True),
        sa.Column('approval_signature', sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(['accounting_proposal_id'], ['accounting_proposals.id'], ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_approvals_accounting_proposal_id'), 'approvals', ['accounting_proposal_id'], unique=False)
        op.create_index(op.f('ix_approvals_user_id'), 'approvals', ['user_id'], unique=False)
        op.create_table('transactions',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('organization_id', sa.Uuid(), nullable=False),
        sa.Column('company_id', sa.Uuid(), nullable=False),
        sa.Column('accounting_proposal_id', sa.Uuid(), nullable=False),
        sa.Column('voucher_type', sa.String(length=50), nullable=False),
        sa.Column('voucher_date', sa.Date(), nullable=False),
        sa.Column('reference_number', sa.String(length=100), nullable=True),
        sa.Column('total_amount', sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column('narration', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['accounting_proposal_id'], ['accounting_proposals.id'], ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('accounting_proposal_id')
        )
        op.create_index(op.f('ix_transactions_company_id'), 'transactions', ['company_id'], unique=False)
        op.create_index(op.f('ix_transactions_organization_id'), 'transactions', ['organization_id'], unique=False)
        op.create_index(op.f('ix_transactions_reference_number'), 'transactions', ['reference_number'], unique=False)
        op.create_table('validation_results',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('accounting_proposal_id', sa.Uuid(), nullable=False),
        sa.Column('rule_code', sa.String(length=100), nullable=False),
        sa.Column('severity', sa.String(length=20), nullable=False),
        sa.Column('is_passed', sa.Boolean(), nullable=False),
        sa.Column('message', sa.Text(), nullable=False),
        sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['accounting_proposal_id'], ['accounting_proposals.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_validation_results_accounting_proposal_id'), 'validation_results', ['accounting_proposal_id'], unique=False)
        op.create_table('posting_jobs',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('organization_id', sa.Uuid(), nullable=False),
        sa.Column('company_id', sa.Uuid(), nullable=False),
        sa.Column('transaction_id', sa.Uuid(), nullable=False),
        sa.Column('bridge_id', sa.Uuid(), nullable=False),
        sa.Column('status', sa.String(length=50), nullable=False),
        sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['bridge_id'], ['bridges.id'], ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='RESTRICT'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_posting_jobs_bridge_id'), 'posting_jobs', ['bridge_id'], unique=False)
        op.create_index(op.f('ix_posting_jobs_company_id'), 'posting_jobs', ['company_id'], unique=False)
        op.create_index(op.f('ix_posting_jobs_organization_id'), 'posting_jobs', ['organization_id'], unique=False)
        op.create_index(op.f('ix_posting_jobs_transaction_id'), 'posting_jobs', ['transaction_id'], unique=False)
        op.create_table('transaction_lines',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('transaction_id', sa.Uuid(), nullable=False),
        sa.Column('line_number', sa.Integer(), nullable=False),
        sa.Column('ledger_id', sa.Uuid(), nullable=False),
        sa.Column('is_debit', sa.Boolean(), nullable=False),
        sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column('item_id', sa.Uuid(), nullable=True),
        sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column('rate', sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['ledger_id'], ['ledgers.id'], ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_transaction_lines_ledger_id'), 'transaction_lines', ['ledger_id'], unique=False)
        op.create_index(op.f('ix_transaction_lines_transaction_id'), 'transaction_lines', ['transaction_id'], unique=False)
        op.create_table('posting_attempts',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('posting_job_id', sa.Uuid(), nullable=False),
        sa.Column('attempt_number', sa.Integer(), nullable=False),
        sa.Column('payload_format', sa.String(length=20), nullable=False),
        sa.Column('payload_sent', sa.Text(), nullable=False),
        sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['posting_job_id'], ['posting_jobs.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_posting_attempts_posting_job_id'), 'posting_attempts', ['posting_job_id'], unique=False)
        op.create_table('posting_responses',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('posting_attempt_id', sa.Uuid(), nullable=False),
        sa.Column('status_code', sa.Integer(), nullable=False),
        sa.Column('raw_response', sa.Text(), nullable=False),
        sa.Column('tally_voucher_guid', sa.String(length=255), nullable=True),
        sa.Column('tally_master_id', sa.Integer(), nullable=True),
        sa.Column('tally_voucher_number', sa.String(length=100), nullable=True),
        sa.Column('is_success', sa.Boolean(), nullable=False),
        sa.Column('error_description', sa.Text(), nullable=True),
        sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['posting_attempt_id'], ['posting_attempts.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_posting_responses_posting_attempt_id'), 'posting_responses', ['posting_attempt_id'], unique=False)
        op.create_index(op.f('ix_posting_responses_tally_voucher_guid'), 'posting_responses', ['tally_voucher_guid'], unique=False)
        op.create_table('verification_results',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('posting_response_id', sa.Uuid(), nullable=False),
        sa.Column('expected_voucher_reference', sa.String(length=100), nullable=True),
        sa.Column('actual_tally_voucher_number', sa.String(length=100), nullable=True),
        sa.Column('tally_guid', sa.String(length=255), nullable=True),
        sa.Column('expected_amount', sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column('actual_amount', sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column('expected_accounting_identity', sa.String(length=255), nullable=True),
        sa.Column('actual_accounting_identity', sa.String(length=255), nullable=True),
        sa.Column('verification_method', sa.String(length=50), nullable=False),
        sa.Column('status', sa.String(length=50), nullable=False),
        sa.Column('mismatch_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('verified_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['posting_response_id'], ['posting_responses.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_verification_results_posting_response_id'), 'verification_results', ['posting_response_id'], unique=False)
        op.create_index(op.f('ix_verification_results_tally_guid'), 'verification_results', ['tally_guid'], unique=False)
        # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
        op.drop_index(op.f('ix_verification_results_tally_guid'), table_name='verification_results')
        op.drop_index(op.f('ix_verification_results_posting_response_id'), table_name='verification_results')
        op.drop_table('verification_results')
        op.drop_index(op.f('ix_posting_responses_tally_voucher_guid'), table_name='posting_responses')
        op.drop_index(op.f('ix_posting_responses_posting_attempt_id'), table_name='posting_responses')
        op.drop_table('posting_responses')
        op.drop_index(op.f('ix_posting_attempts_posting_job_id'), table_name='posting_attempts')
        op.drop_table('posting_attempts')
        op.drop_index(op.f('ix_transaction_lines_transaction_id'), table_name='transaction_lines')
        op.drop_index(op.f('ix_transaction_lines_ledger_id'), table_name='transaction_lines')
        op.drop_table('transaction_lines')
        op.drop_index(op.f('ix_posting_jobs_transaction_id'), table_name='posting_jobs')
        op.drop_index(op.f('ix_posting_jobs_organization_id'), table_name='posting_jobs')
        op.drop_index(op.f('ix_posting_jobs_company_id'), table_name='posting_jobs')
        op.drop_index(op.f('ix_posting_jobs_bridge_id'), table_name='posting_jobs')
        op.drop_table('posting_jobs')
        op.drop_index(op.f('ix_validation_results_accounting_proposal_id'), table_name='validation_results')
        op.drop_table('validation_results')
        op.drop_index(op.f('ix_transactions_reference_number'), table_name='transactions')
        op.drop_index(op.f('ix_transactions_organization_id'), table_name='transactions')
        op.drop_index(op.f('ix_transactions_company_id'), table_name='transactions')
        op.drop_table('transactions')
        op.drop_index(op.f('ix_approvals_user_id'), table_name='approvals')
        op.drop_index(op.f('ix_approvals_accounting_proposal_id'), table_name='approvals')
        op.drop_table('approvals')
        op.drop_index(op.f('ix_extraction_fields_document_extraction_id'), table_name='extraction_fields')
        op.drop_table('extraction_fields')
        op.drop_index('ix_proposals_tenant_status', table_name='accounting_proposals')
        op.drop_index(op.f('ix_accounting_proposals_organization_id'), table_name='accounting_proposals')
        op.drop_index(op.f('ix_accounting_proposals_is_deleted'), table_name='accounting_proposals')
        op.drop_index(op.f('ix_accounting_proposals_document_id'), table_name='accounting_proposals')
        op.drop_index(op.f('ix_accounting_proposals_company_id'), table_name='accounting_proposals')
        op.drop_table('accounting_proposals')
        op.drop_index(op.f('ix_taxes_organization_id'), table_name='taxes')
        op.drop_index(op.f('ix_taxes_company_id'), table_name='taxes')
        op.drop_table('taxes')
        op.drop_index(op.f('ix_sync_runs_sync_job_id'), table_name='sync_runs')
        op.drop_table('sync_runs')
        op.drop_index(op.f('ix_party_identities_party_id'), table_name='party_identities')
        op.drop_index(op.f('ix_party_identities_pan'), table_name='party_identities')
        op.drop_index(op.f('ix_party_identities_gstin'), table_name='party_identities')
        op.drop_table('party_identities')
        op.drop_index(op.f('ix_document_extractions_document_version_id'), table_name='document_extractions')
        op.drop_table('document_extractions')
        op.drop_index(op.f('ix_sync_jobs_organization_id'), table_name='sync_jobs')
        op.drop_index(op.f('ix_sync_jobs_company_id'), table_name='sync_jobs')
        op.drop_table('sync_jobs')
        op.drop_index('ix_parties_tenant', table_name='parties')
        op.drop_index(op.f('ix_parties_tally_guid'), table_name='parties')
        op.drop_index(op.f('ix_parties_organization_id'), table_name='parties')
        op.drop_index(op.f('ix_parties_is_deleted'), table_name='parties')
        op.drop_index(op.f('ix_parties_company_id'), table_name='parties')
        op.drop_table('parties')
        op.drop_index('ix_ledgers_tenant', table_name='ledgers')
        op.drop_index(op.f('ix_ledgers_tally_guid'), table_name='ledgers')
        op.drop_index(op.f('ix_ledgers_organization_id'), table_name='ledgers')
        op.drop_index(op.f('ix_ledgers_is_deleted'), table_name='ledgers')
        op.drop_index(op.f('ix_ledgers_company_id'), table_name='ledgers')
        op.drop_table('ledgers')
        op.drop_index('ix_items_tenant', table_name='items')
        op.drop_index(op.f('ix_items_tally_guid'), table_name='items')
        op.drop_index(op.f('ix_items_organization_id'), table_name='items')
        op.drop_index(op.f('ix_items_is_deleted'), table_name='items')
        op.drop_index(op.f('ix_items_company_id'), table_name='items')
        op.drop_table('items')
        op.drop_index(op.f('ix_document_versions_document_id'), table_name='document_versions')
        op.drop_table('document_versions')
        op.drop_index(op.f('ix_tally_companies_tally_instance_id'), table_name='tally_companies')
        op.drop_index(op.f('ix_tally_companies_tally_guid'), table_name='tally_companies')
        op.drop_index(op.f('ix_tally_companies_company_id'), table_name='tally_companies')
        op.drop_table('tally_companies')
        op.drop_index(op.f('ix_domain_exceptions_organization_id'), table_name='domain_exceptions')
        op.drop_index(op.f('ix_domain_exceptions_company_id'), table_name='domain_exceptions')
        op.drop_table('domain_exceptions')
        op.drop_index('ix_documents_tenant_status', table_name='documents')
        op.drop_index(op.f('ix_documents_sha256_checksum'), table_name='documents')
        op.drop_index(op.f('ix_documents_organization_id'), table_name='documents')
        op.drop_index(op.f('ix_documents_is_deleted'), table_name='documents')
        op.drop_index(op.f('ix_documents_document_number'), table_name='documents')
        op.drop_index(op.f('ix_documents_company_id'), table_name='documents')
        op.drop_table('documents')
        op.drop_index(op.f('ix_connections_session_id'), table_name='connections')
        op.drop_index(op.f('ix_connections_bridge_id'), table_name='connections')
        op.drop_table('connections')
        op.drop_index(op.f('ix_branches_organization_id'), table_name='branches')
        op.drop_index('ix_branches_org_company', table_name='branches')
        op.drop_index(op.f('ix_branches_is_deleted'), table_name='branches')
        op.drop_index(op.f('ix_branches_company_id'), table_name='branches')
        op.drop_table('branches')
        op.drop_index('ix_audit_org_action', table_name='audit_events')
        op.drop_index(op.f('ix_audit_events_recorded_at'), table_name='audit_events')
        op.drop_index(op.f('ix_audit_events_organization_id'), table_name='audit_events')
        op.drop_index(op.f('ix_audit_events_entity_type'), table_name='audit_events')
        op.drop_index(op.f('ix_audit_events_entity_id'), table_name='audit_events')
        op.drop_index(op.f('ix_audit_events_company_id'), table_name='audit_events')
        op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
        op.drop_table('audit_events')
        op.drop_table('user_roles')
        op.drop_table('role_permissions')
        op.drop_index(op.f('ix_companies_pan'), table_name='companies')
        op.drop_index(op.f('ix_companies_organization_id'), table_name='companies')
        op.drop_index('ix_companies_org_active', table_name='companies')
        op.drop_index(op.f('ix_companies_is_deleted'), table_name='companies')
        op.drop_index(op.f('ix_companies_gstin'), table_name='companies')
        op.drop_table('companies')
        op.drop_index(op.f('ix_bridges_tally_instance_id'), table_name='bridges')
        op.drop_index(op.f('ix_bridges_organization_id'), table_name='bridges')
        op.drop_index(op.f('ix_bridges_bridge_client_id'), table_name='bridges')
        op.drop_table('bridges')
        op.drop_index(op.f('ix_users_organization_id'), table_name='users')
        op.drop_index(op.f('ix_users_email'), table_name='users')
        op.drop_table('users')
        op.drop_index(op.f('ix_tally_instances_organization_id'), table_name='tally_instances')
        op.drop_table('tally_instances')
        op.drop_index(op.f('ix_roles_organization_id'), table_name='roles')
        op.drop_table('roles')
        op.drop_index(op.f('ix_permissions_code'), table_name='permissions')
        op.drop_table('permissions')
        op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
        op.drop_table('organizations')
        # ### end Alembic commands ###
